import{S as L,i}from"./assets/vendor-0fc460d7.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const h of t.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&n(h)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();async function f(o,s=1,r=15){const n="https://pixabay.com/api/",e="45098523-0f66f1bf08e0be6a1e71621a5";try{const t=await fetch(`${n}?key=${e}&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&page=${s}&per_page=${r}`);if(!t.ok)throw new Error(t.status);return await t.json()}catch(t){throw new Error(`Failed to fetch images: ${t.message}`)}}const $="../img/icon.svg";function y(o,s=!1){const r=document.querySelector(".gallery");s||(r.innerHTML=""),o.forEach(n=>{const e=document.createElement("a");e.href=n.largeImageURL,e.classList.add("image-card"),e.innerHTML=`
      <img src="${n.webformatURL}" alt="${n.tags}" title="${n.tags}" />
      <div class="info">
        <p><strong>Likes:</strong> ${n.likes}</p>
        <p><strong>Views:</strong> ${n.views}</p>
        <p><strong>Comments:</strong> ${n.comments}</p>
        <p><strong>Downloads:</strong> ${n.downloads}</p>
      </div>
    `,r.appendChild(e)}),window.lightbox?window.lightbox.refresh():window.lightbox=new L(".gallery a",{})}function m(o){const s=document.getElementById("loader");s.style.display="none",i.error({title:"",message:`Failed to fetch images: ${o.message}`,iconUrl:`${$}#icon-Group-1`,position:"topRight",backgroundColor:"red"})}const c="/goit-js-hw-12/assets/icon-8c59a331.svg",w=document.querySelector(".form-inline"),b=document.querySelector(".image-container"),d=document.querySelector(".load-more"),u=document.querySelector(".loader");let l="",g=1,a=0,p=0;w.addEventListener("submit",v);d.addEventListener("click",C);async function v(o){if(o.preventDefault(),l=o.currentTarget.elements.query.value.trim().toLowerCase(),l===""){i.warning({title:"",message:"Search query cannot be empty.",position:"topRight",backgroundColor:"red",icon:"",iconUrl:`${c}#icon-Group-1`});return}g=1,a=0,b.innerHTML="",d.style.display="none",u.style.display="block";try{const r=await f(l,g);p=r.totalHits,r.hits.length>0?(y(r.hits),a+=r.hits.length,a<p?d.style.display="block":i.info({title:"",message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"blue",icon:"",iconUrl:`${c}#icon-Group-1`})):i.warning({title:"",backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",iconUrl:`${c}#icon-Group-1`})}catch(r){m(r)}finally{u.style.display="none",w.reset()}}async function C(){g+=1,u.style.display="block";try{const o=await f(l,g);if(a+=o.hits.length,o.hits.length>0){y(o.hits,!0);const{height:s}=b.firstElementChild.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}a>=p&&(d.style.display="none",i.info({title:"",message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"blue",icon:"",iconUrl:`${c}#icon-Group-1`}))}catch(o){m(o)}finally{u.style.display="none"}}
//# sourceMappingURL=commonHelpers.js.map
