import{S as d,i as c}from"./assets/vendor-0fc460d7.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();function f(s){return fetch(`https://pixabay.com/api/?key=45098523-0f66f1bf08e0be6a1e71621a5&q=${s}&image_type=photo&orientation=horizontal&safesearch=true`).then(o=>{if(!o.ok)throw new Error(o.status);return o.json()})}const g="../img/icon.svg";function m(s){const n=document.querySelector(".gallery");n.innerHTML="",s.forEach(t=>{const o=document.createElement("a");o.href=t.largeImageURL,o.classList.add("image-card"),o.innerHTML=`
      <img src="${t.webformatURL}" alt="${t.tags}" title="${t.tags}" />
      <div class="info">
        <p><strong>Likes:</strong> ${t.likes}</p>
        <p><strong>Views:</strong> ${t.views}</p>
        <p><strong>Comments:</strong> ${t.comments}</p>
        <p><strong>Downloads:</strong> ${t.downloads}</p>
      </div>
    `,n.appendChild(o)}),window.lightbox?window.lightbox.refresh():window.lightbox=new d(".gallery a",{})}function p(s){const n=document.getElementById("loader");n.style.display="none",c.error({title:"",message:`Failed to fetch images: ${s.message}`,iconUrl:`${g}#icon-Group-1`,position:"topRight",backgroundColor:"red"})}const a="/goit-js-hw-12/assets/icon-8c59a331.svg",u=document.querySelector(".form-inline");document.querySelector(".image-container");const l=document.querySelector(".loader");u.addEventListener("submit",h);function h(s){s.preventDefault();const t=s.currentTarget.elements.query.value.trim().toLowerCase();if(t===""){c.warning({title:"",message:"Search query cannot be empty.",position:"topRight",backgroundColor:"red",icon:"",iconUrl:`${a}#icon-Group-1`});return}l.style.display="block",f(t).then(o=>{o.hits.length>0?m(o.hits):c.warning({title:"",backgroundColor:"red",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",iconUrl:`${a}#icon-Group-1`})}).catch(p).finally(()=>{l.style.display="none",u.reset()})}
//# sourceMappingURL=commonHelpers.js.map
